export const GAME = {
  MAP_RADIUS: 3,
  INITIAL_MONEY: 10000,
  BASE_UNIT_COST: 1000,
  UNIT_COST_INCREASE: 50,

  BATTLE_MIN_INTERVAL: 500,
  BATTLE_MAX_INTERVAL: 4000,
  BATTLE_CASUALTY_MIN: 0.2,
  BATTLE_CASUALTY_MAX: 0.35,
  TERRITORIAL_ADVANTAGE_PER_NEIGHBOR: 0.02,
  MAX_TERRITORIAL_ADVANTAGE: 0.12,
  EXPANSION_THRESHOLD: 2,
  PLACEMENT_GRACE_PERIOD: 4000,

  STOCK_COUNT: 5,
  STOCK_MIN_PRICE: 100,
  STOCK_MAX_PRICE: 4000,
  STOCK_UPDATE_MIN: 500,
  STOCK_UPDATE_MAX: 2500,
  STOCK_VOLATILITY: 600,
  STOCK_MEAN_TARGET: 2000,
  STOCK_MEAN_REVERSION: 0.05,

  INITIAL_BULK: 1,
  BULK_UPGRADE_BASE_COST: 5000,
  BULK_UPGRADE_MULTIPLIER: 3,

  NEUTRAL_UNITS_MIN: 5,
  NEUTRAL_UNITS_MAX: 20,

  SERVER_TICK_RATE: 50,
  SERVER_PORT: 12346,
} as const;

export const COMPANY_NAMES = [
  'Quantum Dynamics',
  'Stellar Mining Corp',
  'Nebula Tech',
  'Void Industries',
  'Cosmic Ventures',
  'Galactic Solutions',
  'Nova Enterprises',
  'Eclipse Holdings',
];
